CREATE DATABASE IF NOT EXISTS TIMERCAFEDB;
USE TIMERCAFEDB;

-- 1. CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(100),
    DATA_CADASTRO DATE NOT NULL,
    SALDO_PONTOS INT DEFAULT 0
);

-- 2. RECARGA
CREATE TABLE RECARGA (
    ID_RECARGA INT AUTO_INCREMENT PRIMARY KEY,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_RECARGA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FORMA_PAGAMENTO VARCHAR(45),
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_RECARGA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- 3. COMPUTADOR
CREATE TABLE COMPUTADOR (
    ID_MAQUINA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    STATUS VARCHAR(15) DEFAULT 'DISPONÍVEL',
    PRECO_HORA DECIMAL(10,2) NOT NULL,
    ESPECIFICACOES VARCHAR(255)
);

-- 4. SESSAO
CREATE TABLE SESSAO (
    ID_SESSAO INT AUTO_INCREMENT PRIMARY KEY,
    INICIO_SESSAO DATETIME NOT NULL,
    FIM_SESSAO DATETIME,
    VALOR_TOTAL DECIMAL(10,2),
    STATUS VARCHAR(15),
    ID_CLIENTE INT NOT NULL,
    ID_MAQUINA INT NOT NULL,
    CONSTRAINT FK_SESSAO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_SESSAO_MAQUINA FOREIGN KEY (ID_MAQUINA) REFERENCES COMPUTADOR(ID_MAQUINA)
);

-- 5. PRODUTO
CREATE TABLE PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ESTOQUE INT NOT NULL,
    CATEGORIA VARCHAR(50)
);

-- 6. CONSUMO
CREATE TABLE CONSUMO (
    ID_CONSUMO INT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE INT NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    ID_SESSAO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    CONSTRAINT FK_CONSUMO_SESSAO FOREIGN KEY (ID_SESSAO) REFERENCES SESSAO(ID_SESSAO),
    CONSTRAINT FK_CONSUMO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

-- 7. TORNEIO
CREATE TABLE TORNEIO (
    ID_TORNEIO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    JOGO VARCHAR(80) NOT NULL,
    DATA_TORNEIO DATETIME NOT NULL,
    PREMIO DECIMAL(10,2),
    QUANTIDADE_MAXIMA INT NOT NULL
);

-- 8. INSCRICAO
CREATE TABLE INSCRICAO (
    ID_INSCRICAO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_INSCRICAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'CONFIRMADA',
    ID_CLIENTE INT NOT NULL,
    ID_TORNEIO INT NOT NULL,
    CONSTRAINT FK_INSCRICAO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_INSCRICAO_TORNEIO FOREIGN KEY (ID_TORNEIO) REFERENCES TORNEIO(ID_TORNEIO)
);

-- TABELA AUDIT_LOG
CREATE TABLE AUDIT_LOG (
    ID_AUDIT_LOG INT AUTO_INCREMENT PRIMARY KEY,
    TABELA_AFETADA VARCHAR(50),
    OPERACAO VARCHAR(20),
    DATA_LOG DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO VARCHAR(50),
    DESCRICAO TEXT
);