-- 03_indexes.sql
-- Execute após 01_schema.sql para adicionar índices de performance

USE TIMERCAFEDB;

-- SESSAO: buscas frequentes por cliente, máquina e status
CREATE INDEX IDX_SESSAO_CLIENTE ON SESSAO(ID_CLIENTE);
CREATE INDEX IDX_SESSAO_MAQUINA ON SESSAO(ID_MAQUINA);
CREATE INDEX IDX_SESSAO_STATUS  ON SESSAO(STATUS);

-- COMPUTADOR: filtro de status usado em toda listagem
CREATE INDEX IDX_COMPUTADOR_STATUS ON COMPUTADOR(STATUS);

-- INSCRICAO: buscas por cliente e torneio
CREATE INDEX IDX_INSCRICAO_CLIENTE  ON INSCRICAO(ID_CLIENTE);
CREATE INDEX IDX_INSCRICAO_TORNEIO  ON INSCRICAO(ID_TORNEIO);

-- CONSUMO: joins com sessão e produto
CREATE INDEX IDX_CONSUMO_SESSAO  ON CONSUMO(ID_SESSAO);
CREATE INDEX IDX_CONSUMO_PRODUTO ON CONSUMO(ID_PRODUTO);

-- RECARGA: buscas por cliente
CREATE INDEX IDX_RECARGA_CLIENTE ON RECARGA(ID_CLIENTE);
